# Sean Kaliszewski
## Week 10 - 3/28/21
### Python Numpy - Process

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]
print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
my_arr = np.array(my_list)

In [5]:
print(my_arr.dtype)

int32


In [6]:
fruits = ['Orange', 'Apple', 'Cherry', 'Grape']
my_strArr = np.array(fruits)

In [7]:
print(my_strArr.dtype)

<U6


In [8]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')

In [9]:
print(my_arr2.dtype)

|S2


In [10]:
my_arr2 = np.array([1,2,3,4,5], dtype='S')
print(my_arr2.dtype)

|S1


In [11]:
my_arr3 = np.array([5,6,7,8,9], dtype='i4')

In [12]:
print(my_arr3)
print(my_arr3.dtype)

[5 6 7 8 9]
int32


In [13]:
my_errArr = np.array(['1', '2', '3', '4', '5'], dtype='i')

In [14]:
print(my_errArr)

[1 2 3 4 5]


In [15]:
scores = [78.5,88.9,90.3,89.9]
my_arr = np.array(scores)

In [16]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [17]:
arr = my_arr.astype('i')

In [18]:
print(arr)

[78 88 90 89]


In [19]:
bool_arr = arr.astype('b')

In [20]:
print(arr)
print(bool_arr)

[78 88 90 89]
[78 88 90 89]


In [25]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]
my_list = [lst1,lst2]
my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [26]:
#numpy built-in functions to generate arrays from existing array
#copy and view, instead of using =
my_list = [11,12,13,14,15]
arr = np.array(my_list)
c_arr = arr.copy()
print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [27]:
arr[3]=4
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [28]:
#view
my_list = [11,12,13,14,15]
arr = np.array(my_list)
v_arr = arr.view()
print(arr)
print(v_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [29]:
v_arr[2]=3
print(arr)
print(v_arr)

[11 12  3 14 15]
[11 12  3 14 15]


In [30]:
print(c_arr.base)
print(v_arr.base)

None
[11 12  3 14 15]


In [31]:
#shape gives the number of elements in each dimension

In [32]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]
my_list=[lst1,lst2]
my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)
print(my_arr.shape)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2
(2, 5)


In [33]:
#shape returns 2 dimensions and each dimension has 5 elements

In [36]:
arr = np.array(lst1, ndmin=6)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)


In [35]:
#each index in the shape tells the number of elements in that dimension