# Sean Kaliszewski
## Week 11 - 4/4/21
### Python Numpy Creating, Processing, Trasnporting Arrays

In [2]:
import numpy as np
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print(arr.ndim)
print(arr.dtype)

1
float64


In [5]:
arr_2d = np.zeros((5,5))
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
float64


In [8]:
arr = np.ones((5,5))
print(arr)
print(arr.ndim)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [9]:
arr = np.empty((5,5))
print(arr)
print(arr.ndim)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [10]:
arr = np.empty((2,2))
print(arr)
print(arr.ndim)
print(arr.dtype)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]
2
float64


In [11]:
arr = np.empty((3,3), dtype = int)
print(arr)
print(arr.ndim)
print(arr.dtype)

[[          0           0   620805152]
 [        574           0           0]
 [-2147483648           0           0]]
2
int32


In [12]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [16]:
arr = np.arange(10,100,5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)
1
int32


In [18]:
arr = np.arange(1,13,1)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [19]:
arr_2d = arr.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
arr_2d = arr.reshape(4,3)
print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
#reshape 1-d to 3-d
arr_3d = arr.reshape(3,2,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [22]:
arr_3d = arr.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
arr_2d = arr.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [24]:
#reshape is a view or copy
print(arr_2d.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
arr_3d = arr.reshape(2,2,-1)
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [26]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

In [27]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
#iterating 1-d
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [30]:
#iterating 2-d
arr = np.array([[1,2,3,4], [5,6,7,8]])
for n in arr:
    print(n)

[1 2 3 4]
[5 6 7 8]


In [32]:
for n in arr:
    for x in n:
        print(x)

1
2
3
4
5
6
7
8


In [33]:
#iterating 3-d
arr_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
print(arr_3d)
print(arr_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [34]:
for n in arr_3d:
    print(n)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [35]:
for n3 in arr_3d:
    for n2 in n3:
        for n1 in n2:
            print(n1)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
for n in np.nditer(arr_3d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [37]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
arr_2d[:,::2]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [40]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

1
3
4
6
7
9
10
12


In [41]:
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [43]:
for i, n in np.ndenumerate(arr):
    print(i,n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [44]:
arr_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr_2d.shape)

(4, 2)


In [46]:
for i, v in np.ndenumerate(arr_2d):
    print(i,v)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8


In [47]:
arr_2d * arr_2d

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [48]:
arr_2d - arr_2d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [49]:
arr_2d + arr_2d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [50]:
arr_2d**3

array([[  1,   8],
       [ 27,  64],
       [125, 216],
       [343, 512]], dtype=int32)

In [51]:
1 / arr_2d

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667],
       [0.14285714, 0.125     ]])

In [52]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [55]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
arr[::3]

array([ 1,  4,  7, 10])

In [57]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [58]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
arr[0:6] = 100

In [60]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [61]:
import numpy as np
arr_2d = np.array([[5,10,25], [15,10,20],[20,30,35]])
print(arr_2d.shape)
print(arr_2d)

(3, 3)
[[ 5 10 25]
 [15 10 20]
 [20 30 35]]


In [62]:
arr_2d[1]

array([15, 10, 20])

In [63]:
arr_2d[1,0]

15

In [64]:
#slicing
arr_2d[:2,1:]

array([[10, 25],
       [10, 20]])

In [65]:
arr_2d[2]

array([20, 30, 35])

In [66]:
arr_2d[2,-1]

35

In [68]:
arr = np.zeros((9,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
arr.shape

(9, 9)

In [70]:
arr.shape[0]

9

In [71]:
arr.shape[2]

IndexError: tuple index out of range

In [77]:
l = arr.shape[0]

for idx in range(l):
    arr[idx]=10
    
arr

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [80]:
for idx in range(l):
    arr[idx]=idx*2
arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [81]:
arr[1:7]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.]])

In [82]:
arr[1:7,3:6]

array([[ 2.,  2.,  2.],
       [ 4.,  4.,  4.],
       [ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [10., 10., 10.],
       [12., 12., 12.]])

In [83]:
arr[::2,3:6]

array([[ 0.,  0.,  0.],
       [ 4.,  4.,  4.],
       [ 8.,  8.,  8.],
       [12., 12., 12.],
       [16., 16., 16.]])

In [84]:
arr[[1,6,7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [85]:
arr[[3,5]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [87]:
#reshape
arr = np.arange(45).reshape(9,5)

#output
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [88]:
arr_t = arr.T

#output
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [89]:
np.dot(arr_t,arr)

array([[5100, 5280, 5460, 5640, 5820],
       [5280, 5469, 5658, 5847, 6036],
       [5460, 5658, 5856, 6054, 6252],
       [5640, 5847, 6054, 6261, 6468],
       [5820, 6036, 6252, 6468, 6684]])

In [91]:
arr_3d = np.arange(45).reshape(3,5,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [92]:
#swapaxes
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [93]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])