# Sean Kaliszewski
## Week 11 - 4/4/21
### Python NumPy Universal Functions

In [1]:
import numpy as np
arr1 = [1,2,3,4,5,6,7,8,9]
arr2 = [11,12,13,14,15,16,17,18]
z = []
for i, j in zip(arr1,arr2):
    z.append(i + j)
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [2]:
#zip
fname = ('Alice', 'Bob', 'Christy')
lname = ('Charlie', 'Clark', 'Robert')
flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [3]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [4]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
arr1 = np.random.randn(10)
arr1

array([ 1.16897182, -0.04671807,  0.14058392, -0.0476547 , -1.06568226,
        0.66923316, -0.73749605, -0.30189445,  1.26805296, -0.98595679])

In [9]:
arr2 = np.random.randn(10)
arr2

array([-0.59436528,  1.0821858 , -0.63247175,  0.66549747, -0.10919206,
        0.33011089,  1.80628407,  0.34166596, -0.5593197 ,  0.6804331 ])

In [10]:
np.add(arr1,arr2)

array([ 0.57460654,  1.03546773, -0.49188783,  0.61784278, -1.17487432,
        0.99934404,  1.06878802,  0.03977151,  0.70873326, -0.30552369])

In [11]:
np.maximum(arr1,arr2)

array([ 1.16897182,  1.0821858 ,  0.14058392,  0.66549747, -0.10919206,
        0.66923316,  1.80628407,  0.34166596,  1.26805296,  0.6804331 ])

In [12]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print(arr<4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
np.where(arr<4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [15]:
np.where((arr<4)&(arr>2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [17]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [18]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [19]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
cond = np.array([[True, False], [True, True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [20]:
np.where([[True, False], [True, True]], [[5,6], [7,8]], [[1,2], [3,4]])

array([[5, 2],
       [7, 8]])

In [23]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[-0.53543304, -0.541905  ,  0.42743271],
       [ 1.17852962, -1.00996945,  2.4686938 ],
       [-0.48525559, -0.76793747,  1.59374439]])

In [24]:
np.where(arr<0, 0,1)

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]])

In [25]:
np.where(arr<0, 0,arr)

array([[0.        , 0.        , 0.42743271],
       [1.17852962, 0.        , 2.4686938 ],
       [0.        , 0.        , 1.59374439]])

In [26]:
arr_b = np.array([True,False,True,False,False])
arr_b.any()

True

In [27]:
arr_b.all()

False

In [28]:
fruits = np.array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [30]:
np.in1d(['Apple', 'Cherry', 'Grape'], fruits)

array([ True,  True, False])

In [31]:
#statistical measures
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
arr.sum()

45

In [33]:
arr.sum(0)

array([12, 15, 18])

In [34]:
arr.sum(1)

array([ 6, 15, 24])

In [35]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [36]:
print(arr)
np.sum(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [38]:
print(arr)
np.sum(arr, axis=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [39]:
arr.mean()

5.0

In [40]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [41]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [42]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [43]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [44]:
arr.var()

6.666666666666667

In [46]:
arr.std()

2.581988897471611

In [47]:
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])
arr.sort()
arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [48]:
#identify array
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [51]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)
a * i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [52]:
m = np.mat([[1,2], [3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [53]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [54]:
#Transpose
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)
print(arr)
print('------------------')
t = arr.T
t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
------------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [55]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [56]:
arr.transpose(0,1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [58]:
arr_3d = np.arange(20).reshape((2,5,2))
print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [59]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [61]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [62]:
np.random.random((4,4))

array([[0.79613327, 0.08257255, 0.31410502, 0.84661482],
       [0.80732918, 0.42410487, 0.3168144 , 0.5586674 ],
       [0.5185613 , 0.75608423, 0.07839708, 0.61174468],
       [0.87201149, 0.23197579, 0.36245347, 0.33628587]])

In [64]:
from numpy.random import random
random((4,4))

array([[0.2750219 , 0.77703751, 0.07025496, 0.46422111],
       [0.9386911 , 0.05355668, 0.66507092, 0.15598914],
       [0.9939523 , 0.22655526, 0.05840255, 0.81173465],
       [0.3072777 , 0.52898052, 0.53546179, 0.43968562]])

In [65]:
from numpy.random import randn
randn(5,5)

array([[ 0.24151619,  0.11494427,  0.32415574,  1.85625994,  0.07943094],
       [-1.09127884,  0.00698833, -0.08927719,  2.41059963, -0.81464053],
       [ 2.41162135,  0.66610203, -1.74375057,  1.85356568,  0.86666489],
       [-1.51130503, -0.56561683,  0.31550905, -0.28489555, -1.19459333],
       [ 1.07645095, -0.08643128, -1.41299628,  0.12317519,  2.50064154]])

In [66]:
randn(5)

array([-1.06685218, -0.26097042,  0.38944624, -0.03070249,  1.68796401])

In [67]:
np.random.randint(10,50)

36

In [68]:
import pandas as pd