# Sean Kaliszewski
## Week 11 - 4/4/21
### Python NumPy Universal Functions

In [2]:
import numpy as np
arr1 = [1,2,3,4,5,6,7,8,9]
arr2 = [11,12,13,14,15,16,17,18]
z = []
for i, j in zip(arr1,arr2):
    z.append(i + j)
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [4]:
#zip
fname = ('Alice', 'Bob', 'Christy')
lname = ('Charlie', 'Clark', 'Robert')
flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [6]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [7]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
arr1 = np.random.randn(10)
arr1

array([-2.40491389, -0.36935233,  1.78894632,  1.59653032,  1.41645373,
        1.76805455,  1.02780716, -0.81684917, -1.48197793, -0.4614298 ])

In [13]:
arr2 = np.random.randn(10)
arr2

array([-0.14675988,  2.36245031, -0.68236318, -2.02518147,  0.2514737 ,
       -0.17558413,  0.96359589, -0.7182017 ,  0.22715356,  1.68839528])

In [14]:
np.add(arr1,arr2)

array([-2.55167377,  1.99309797,  1.10658314, -0.42865114,  1.66792743,
        1.59247042,  1.99140305, -1.53505087, -1.25482437,  1.22696548])

In [15]:
np.maximum(arr1,arr2)

array([-0.14675988,  2.36245031,  1.78894632,  1.59653032,  1.41645373,
        1.76805455,  1.02780716, -0.7182017 ,  0.22715356,  1.68839528])

In [16]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
print(arr<4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [18]:
np.where(arr<4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [20]:
np.where((arr<4)&(arr>2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [22]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [26]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [27]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])